---
version: 2.1

commands:
  restore_point:
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - repository-{{ checksum ".circle-sha" }}
  save_point:
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: repository-{{ checksum ".circle-sha" }}
          paths:
            - .

jobs:
  checkout_source:
    docker:
      - image: circleci/node:12.18.4-stretch
    steps:
      - checkout
      - save_point
  test:
    docker:
      - image: circleci/node:12.18.4-stretch
      - image: highoutputdev/activemq:latest
      - image: mongo:latest
      - image: rabbitmq:3.8-rc-alpine
        name: 'rabbitmq'
    steps:
      - restore_point
      - run:
          name: bootstrap
          command: npx lerna bootstrap
      - run:
          name: lint
          command: npx lerna run lint
      - run:
          name: typecheck
          command: npx lerna run typecheck
      - run:
          name: test
          command: npx lerna run test

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout_source
      - test:
          requires:
            - checkout_source